"""Agent domain events."""

EVENT_PIPELINE_STARTED = "agent.pipeline.started"
EVENT_PIPELINE_COMPLETED = "agent.pipeline.completed"
EVENT_PIPELINE_FAILED = "agent.pipeline.failed"
EVENT_STAGE_STARTED = "agent.stage.started"
EVENT_STAGE_COMPLETED = "agent.stage.completed"
EVENT_SUBAGENT_STARTED = "agent.subagent.started"
EVENT_SUBAGENT_COMPLETED = "agent.subagent.completed"
EVENT_SUBAGENT_FAILED = "agent.subagent.failed"
EVENT_RALPH_LOOP_STARTED = "agent.ralph_loop.started"
EVENT_RALPH_LOOP_ITERATION = "agent.ralph_loop.iteration"
EVENT_RALPH_LOOP_APPROVED = "agent.ralph_loop.approved"
EVENT_RALPH_LOOP_MAX_ITERATIONS = "agent.ralph_loop.max_iterations"
