"""Agent domain repository protocols."""

from __future__ import annotations

import uuid
from typing import Protocol

from .entities import Agent, AgentPipeline, AgentRun, RalphLoop


class AgentRunRepository(Protocol):
    async def get(self, id: uuid.UUID) -> AgentRun | None: ...
    async def save(self, run: AgentRun) -> None: ...


class AgentRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Agent | None: ...
    async def get_by_name(self, name: str) -> Agent | None: ...
    async def list_all(self) -> list[Agent]: ...
    async def save(self, agent: Agent) -> None: ...


class AgentPipelineRepository(Protocol):
    async def get(self, id: uuid.UUID) -> AgentPipeline | None: ...
    async def get_by_name(self, name: str) -> AgentPipeline | None: ...
    async def save(self, pipeline: AgentPipeline) -> None: ...


class RalphLoopRepository(Protocol):
    async def get(self, id: uuid.UUID) -> RalphLoop | None: ...
    async def get_by_run_id(self, agent_run_id: uuid.UUID) -> RalphLoop | None: ...
    async def save(self, loop: RalphLoop) -> None: ...
