"""Style domain repository protocols."""

from __future__ import annotations

import uuid
from typing import Protocol

from .entities import StylePreset, StyleProfile


class StyleProfileRepository(Protocol):
    async def get(self, id: uuid.UUID) -> StyleProfile | None: ...
    async def save(self, profile: StyleProfile) -> None: ...
    async def delete(self, id: uuid.UUID) -> None: ...
    async def list_all(self, limit: int = 50, offset: int = 0) -> list[StyleProfile]: ...


class StylePresetRepository(Protocol):
    async def get(self, id: uuid.UUID) -> StylePreset | None: ...
    async def get_by_name(self, name: str) -> StylePreset | None: ...
    async def save(self, preset: StylePreset) -> None: ...
    async def list_all(self, limit: int = 100, offset: int = 0) -> list[StylePreset]: ...
