from __future__ import annotations

import uuid
from typing import Protocol

from .entities import User


class UserRepository(Protocol):
    async def get(self, id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> None: ...
    async def delete(self, id: uuid.UUID) -> None: ...
