"""Content domain repository protocols."""

from __future__ import annotations

import uuid
from typing import Protocol

from .entities import ContentPlan, SlideContent, SystemPrompt


class ContentPlanRepository(Protocol):
    async def get(self, id: uuid.UUID) -> ContentPlan | None: ...
    async def save(self, plan: ContentPlan) -> None: ...
    async def delete(self, id: uuid.UUID) -> None: ...


class SlideContentRepository(Protocol):
    async def get(self, id: uuid.UUID) -> SlideContent | None: ...
    async def get_by_plan_and_index(
        self, plan_id: uuid.UUID, slide_index: int
    ) -> SlideContent | None: ...
    async def save(self, content: SlideContent) -> None: ...
    async def delete(self, id: uuid.UUID) -> None: ...


class SystemPromptRepository(Protocol):
    async def get(self, id: uuid.UUID) -> SystemPrompt | None: ...
    async def get_by_name(self, name: str) -> SystemPrompt | None: ...
    async def save(self, prompt: SystemPrompt) -> None: ...
    async def list_all(self) -> list[SystemPrompt]: ...
    async def delete(self, id: uuid.UUID) -> None: ...
